### ISSUE TITLE
error predicting some smiles

### ISSUE THREAD

**Issue by Limmiche** [Xundrug/MolTaut#1]
Hello @xiaolinpan

**Description**
I have an issue running MolTaut in python with certain smiles:
```
python predict_tautomer.py --smi CC1=CNC(=O)NC1=O 
zsh: no matches found: CC1=CNC(=O)NC1=O
```
However some smiles seem to work:

```
python predict_tautomer.py --smi CCCCCCCCCCCCCO
[{'tsmi': 'CCCCCCCCCCCCCO', 'psmis': ['CCCCCCCCCCCCCO'], 'score': '0.0', 'label': 'low_energy'}]

```

Both smiles however work in the web version 
http://moltaut.xundrug.cn/

**Configuration**

  RDKit version: 2022.09.1 
  OS: macOS
  Python version (if relevant): 3.10.8

**Comment by xiaolinpan** [comment]
Thank you for reporting the bug. I will check it at once.

**Comment by xiaolinpan** [comment]
It will work like this. The Smiles string should add a quote.

`python predict_tautomer.py --smi "CC1=CNC(=O)NC1=O"`
