### ISSUE TITLE
Using MolTaut on big dataset

### ISSUE THREAD

**Issue by Limmiche** [Xundrug/MolTaut#2]
Hello @xiaolinpan,

I have been using MolTaut for a while now and wondered how to properly apply the script on a dataframe with 70K smiles strings. Do you have any suggestions on how to quickly calculate the strings?

**Comment by xiaolinpan** [comment]
Thank you for your interest. I have been infected with covid-19, so the reply is late. 

If you have a high-performance computational resource, I think it will be fastly done for 70K smiles.

In addition, I'm constructing a tautomer database using the ML scoring method (MolTaut) for faster calculations,  it will be released later. It will be very fast in the next version.

**Comment by Limmiche** [comment]
I am sorry to hear that, I hope you are doing better now and had a happy new year. Is it possible to use multiprocessing for calculating 70K smiles on top of your script, which already uses multiprocessing? Or do you recommend calculating the tautomers sequentially?
